// File generated by FlutterFire CLI.
//
//----------------   ## ----------------------------------------
//----------------   ## ----------------------------------------

// Edw mesa exw oles tis plhrofories gia th bash tou firebase pou exw sindese
// DEN TA PEIRAZW MEXRI NA MATHW TI MOY GINETAI AKRIBOS

//----------------   ## ----------------------------------------
//----------------   ## ----------------------------------------

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjF-CKpH4QgfH0Z6RkwGgh1_UX25q4hVs',
    appId: '1:612333448315:web:73838af25405612e6286de',
    messagingSenderId: '612333448315',
    projectId: 'chatify-udemy-aae94',
    authDomain: 'chatify-udemy-aae94.firebaseapp.com',
    storageBucket: 'chatify-udemy-aae94.appspot.com',
    measurementId: 'G-K83DMJC29C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qPYjvSxExt_kLsGmcGTquAawZjMeBzc',
    appId: '1:612333448315:android:4163120ce26d11946286de',
    messagingSenderId: '612333448315',
    projectId: 'chatify-udemy-aae94',
    storageBucket: 'chatify-udemy-aae94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rckjWjb0o1BnojuR7saYKC876SKEWR4',
    appId: '1:612333448315:ios:9d9f8d4e9a7bcca76286de',
    messagingSenderId: '612333448315',
    projectId: 'chatify-udemy-aae94',
    storageBucket: 'chatify-udemy-aae94.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rckjWjb0o1BnojuR7saYKC876SKEWR4',
    appId: '1:612333448315:ios:f8d7e78a91d8664c6286de',
    messagingSenderId: '612333448315',
    projectId: 'chatify-udemy-aae94',
    storageBucket: 'chatify-udemy-aae94.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
